// Auto-generated by scripts/generate-kie-image.js.
// Do not put API keys in this file.
module.exports = [
  {
    "name": "peach-premium-box",
    "title": "精品大果桃礼盒",
    "src": "/uploads/seed-images/peach-premium-box.png",
    "prompt": "Luxury premium large peach gift box for presale: big flawless peaches arranged in an elegant rigid gift box with subtle ribbon, premium holiday gifting atmosphere, soft cream and blush background, studio product photography, high-end ecommerce banner, no text, no logo, no watermark.",
    "model": "gpt-image-2-text-to-image",
    "aspectRatio": "16:9",
    "taskId": "e7bdadf551cb5667c6a7c52d116fa81a",
    "createdAt": "2026-05-14T01:24:28.379Z"
  },
  {
    "name": "peach-family-bag",
    "title": "家庭尝鲜袋装桃",
    "src": "/uploads/seed-images/peach-family-bag.png",
    "prompt": "Fresh family pack peaches for ecommerce: ripe honey peaches in a simple kraft paper bag and breathable mesh produce bag, casual home kitchen table, friendly affordable feeling, warm sunlight, natural green leaves, clean pastel background, realistic high-quality product photography, no text, no logo, no watermark.",
    "model": "gpt-image-2-text-to-image",
    "aspectRatio": "16:9",
    "taskId": "24c06ecb30606ce10941271b5ac384e3",
    "createdAt": "2026-05-14T01:23:37.163Z"
  },
  {
    "name": "peach-early-summer-box",
    "title": "早夏水蜜桃预售礼盒",
    "src": "/uploads/seed-images/peach-early-summer-box.png",
    "prompt": "Premium commercial product photo for a peach presale mini program: elegant white and soft-pink gift box opened with fresh juicy early-summer honey peaches inside, a few whole peaches and green leaves on a clean warm table, soft natural morning light, pastel peach and cream palette, refined ecommerce hero image, no text, no logo, no watermark.",
    "model": "gpt-image-2-text-to-image",
    "aspectRatio": "16:9",
    "taskId": "3f73afdb99660bc5f2592a86bd441956",
    "createdAt": "2026-05-14T01:23:06.816Z"
  },
  {
    "name": "test-showcase",
    "title": "测试展示图",
    "src": "/uploads/seed-images/test-showcase.png",
    "prompt": "A soft pastel illustration for a WeChat mini program image showcase card, clean mobile UI frame, gentle pink and mint accents, high quality, no text, no logo",
    "model": "gpt-image-2-text-to-image",
    "aspectRatio": "16:9",
    "taskId": "db535b60a144f8d3ec6d27b5a89d7c4d",
    "createdAt": "2026-05-13T05:52:08.059Z"
  }
];
